const path = require('path');
const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
const cookieParser = require('cookie-parser');
const publicRoutes = require('./routes/publicRoutes');
const adminRoutes = require('./routes/adminRoutes');
const authRoutes = require('./routes/authRoutes');
const customerRoutes = require('./routes/customerRoutes');
const staffRoutes = require('./routes/staffRoutes');
const notificationRoutes = require('./routes/notificationRoutes');
const supportRoutes = require('./routes/supportRoutes');
const { authenticate, requireRole } = require('./middleware/authenticate');
const { notFound, errorHandler } = require('./middleware/errorHandler');
const { apiLimiter, leadLimiter, authLimiter, registrationLimiter, customerRequestLimiter, chatMessageLimiter, supportMessageLimiter, rejectUnsafeKeys } = require('./middleware/security');

const app = express();
app.disable('x-powered-by');
if (process.env.TRUST_PROXY) app.set('trust proxy', Number(process.env.TRUST_PROXY) || process.env.TRUST_PROXY);
app.use(helmet({ crossOriginResourcePolicy: { policy: 'cross-origin' } }));
const allowedOrigins = (process.env.CLIENT_URL || 'http://localhost:3000').split(',').map(value => value.trim());
app.use(cors({ origin: (origin, callback) => !origin || allowedOrigins.includes(origin) ? callback(null, true) : callback(Object.assign(new Error('Origin không được phép'), { status: 403 })), credentials: true }));
app.use(express.json({ limit: '2mb' }));
app.use(express.urlencoded({ extended: true, limit: '2mb' }));
app.use(cookieParser());
if (process.env.NODE_ENV !== 'test') app.use(morgan('dev'));
app.use('/uploads/content', express.static(path.join(__dirname, '..', 'storage', 'content-images'), { dotfiles: 'deny', index: false, maxAge: '7d' }));
app.use('/api', apiLimiter, rejectUnsafeKeys);
app.use('/api/leads', leadLimiter);
app.use('/api/auth/login', authLimiter);
app.use('/api/auth/forgot-password', authLimiter);
app.use('/api/auth/reset-password', authLimiter);
app.use('/api/auth/register', registrationLimiter);
app.use('/api/customer/requests', customerRequestLimiter);
app.use('/api/customer/requests/:id/messages', chatMessageLimiter);
app.use('/api/staff/requests/:id/messages', chatMessageLimiter);
app.use('/api/support/messages', supportMessageLimiter);
app.use('/api/support/conversations/:id/messages', supportMessageLimiter);
app.use('/api/auth', authRoutes);
app.use('/api/support', supportRoutes);
app.use('/api/notifications', authenticate, notificationRoutes);
app.use('/api/customer', authenticate, requireRole('customer'), customerRoutes);
app.use('/api/staff', authenticate, requireRole('staff', 'admin'), staffRoutes);
app.use('/api', publicRoutes);
app.use('/api/admin', authenticate, requireRole('admin'), adminRoutes);
app.use(notFound);
app.use(errorHandler);

module.exports = app;
