import { useQuery } from "@tanstack/react-query"
import { ArrowRight, BadgeCheck, Box, Building2, Check, ChevronRight, ClipboardCheck, Cog, Factory, Gauge, Headphones, Phone, Ruler, ShieldCheck, Wrench } from "lucide-react"
import { Link, useOutletContext } from "react-router-dom"
import { BlurText } from "@/components/react-bits/blur-text"
import { CountUp } from "@/components/react-bits/count-up"
import { FadeContent } from "@/components/react-bits/fade-content"
import { Button } from "@/components/ui/button"
import { fallbackProducts, fallbackProjects } from "@/data/fallback"
import { api } from "@/lib/api"
import { formatPrice } from "@/lib/utils"
import type { LayoutContext } from "@/components/app-layout"

const services = [
  { icon: Ruler, title: "Tư vấn kỹ thuật", text: "Khảo sát, thiết kế giải pháp và tối ưu dây chuyền đúng mục tiêu sản xuất." },
  { icon: Cog, title: "Gia công cơ khí", text: "Cắt, chấn, hàn, tiện CNC và chế tạo chi tiết chính xác theo bản vẽ." },
  { icon: Factory, title: "Thi công công nghiệp", text: "Nhà xưởng, kết cấu thép, hệ thống M&E và lắp đặt thiết bị trọn gói." },
  { icon: Box, title: "Cung ứng thiết bị", text: "Vật tư, linh kiện và thiết bị công nghiệp có nguồn gốc rõ ràng." },
]

export function HomePage() {
  const { openQuote } = useOutletContext<LayoutContext>()
  const projectQuery = useQuery({ queryKey: ["projects", "featured"], queryFn: api.projects, staleTime: 5 * 60_000, retry: 1 })
  const productQuery = useQuery({ queryKey: ["products", "featured"], queryFn: api.products, staleTime: 5 * 60_000, retry: 1 })
  const projects = projectQuery.data?.data?.length ? projectQuery.data.data : fallbackProjects
  const products = productQuery.data?.data?.length ? productQuery.data.data : fallbackProducts

  return <>
    <section className="relative isolate min-h-[680px] overflow-hidden bg-emerald-950 text-white lg:min-h-[720px]">
      <img className="absolute inset-0 -z-20 size-full object-cover opacity-45" src="https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?auto=format&fit=crop&w=2000&q=85" alt="Nhà máy gia công cơ khí hiện đại" fetchPriority="high" />
      <div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,rgba(8,38,31,.97)_0%,rgba(8,38,31,.82)_48%,rgba(8,38,31,.2)_100%)]" />
      <div className="container-page flex min-h-[680px] items-center py-20 lg:min-h-[720px]"><div className="max-w-3xl"><p className="mb-6 flex items-center gap-3 text-xs font-extrabold uppercase tracking-[.22em] text-orange-300"><span className="h-0.5 w-9 bg-orange-500" />Đối tác kỹ thuật đáng tin cậy</p><h1 className="font-display text-[clamp(2.7rem,6vw,5.4rem)] font-semibold leading-[1.04] tracking-[-.045em]"><BlurText text="Giải pháp cơ khí" /><span className="block text-orange-400"><BlurText text="chính xác & toàn diện." /></span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-emerald-50/80 sm:text-xl">Từ tư vấn, chế tạo đến lắp đặt — DK Industry giúp doanh nghiệp vận hành hiệu quả bằng giải pháp kỹ thuật rõ ràng và bền vững.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button size="lg" onClick={() => openQuote()}>Trao đổi dự án <ArrowRight className="size-5" /></Button><Button size="lg" variant="outline" asChild className="border-white/30 bg-white/10 text-white hover:bg-white hover:text-emerald-950"><Link to="/du-an">Xem năng lực thực tế</Link></Button></div><div className="mt-10 flex flex-wrap gap-x-7 gap-y-3 text-sm font-semibold text-emerald-50/70">{["Khảo sát tận nơi", "Báo giá minh bạch", "Bảo hành rõ ràng"].map(item => <span className="flex items-center gap-2" key={item}><Check className="size-4 text-orange-400" />{item}</span>)}</div></div></div>
    </section>

    <section aria-label="Thành tựu" className="border-b border-slate-200 bg-white"><div className="container-page grid grid-cols-2 divide-x divide-y divide-slate-200 lg:grid-cols-4 lg:divide-y-0">{[[12,"+","Năm kinh nghiệm"],[350,"+","Dự án hoàn thành"],[98,"%","Khách hàng hài lòng"],[24,"/7","Hỗ trợ kỹ thuật"]].map(([number,suffix,label]) => <div className="px-4 py-7 text-center sm:py-9" key={String(label)}><strong className="font-display text-3xl font-extrabold text-orange-600 sm:text-4xl"><CountUp to={Number(number)} suffix={String(suffix)} /></strong><span className="mt-2 block text-sm font-bold text-slate-600">{label}</span></div>)}</div></section>

    <section className="section-space bg-white"><div className="container-page grid items-center gap-12 lg:grid-cols-2 lg:gap-20"><FadeContent><div className="relative"><img className="aspect-[4/3] w-full rounded-3xl object-cover" loading="lazy" src="https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&w=1200&q=82" alt="Kỹ sư DK Industry kiểm tra thiết bị"/><div className="absolute -bottom-5 -right-2 rounded-2xl bg-orange-600 p-5 text-white shadow-xl sm:right-5"><ShieldCheck className="mb-2 size-7"/><strong className="block text-lg">Chất lượng kiểm soát</strong><span className="text-sm text-orange-100">Ở mọi công đoạn</span></div></div></FadeContent><FadeContent delay={.08}><SectionTag>Về DK Industry</SectionTag><h2 className="heading-section">Hiểu kỹ thuật.<br/><span>Giữ trọn cam kết.</span></h2><p className="mt-6 text-lg leading-8 text-slate-600">Chúng tôi kết hợp kinh nghiệm thực tiễn, công nghệ hiện đại và trách nhiệm nghề nghiệp để tạo ra giải pháp phù hợp cho từng nhà máy.</p><div className="mt-7 grid gap-4 sm:grid-cols-2">{[[BadgeCheck,"Vật tư rõ nguồn gốc"],[Gauge,"Tiến độ được kiểm soát"],[Wrench,"Đội ngũ giàu kinh nghiệm"],[Headphones,"Hỗ trợ sau bàn giao"]].map(([Icon,label]) => { const C = Icon as typeof BadgeCheck; return <div className="flex items-center gap-3 text-sm font-bold text-slate-800" key={String(label)}><span className="grid size-10 place-items-center rounded-xl bg-emerald-50 text-emerald-800"><C className="size-5" /></span>{String(label)}</div>})}</div><Button asChild variant="dark" className="mt-8"><Link to="/dich-vu">Tìm hiểu năng lực <ArrowRight className="size-5" /></Link></Button></FadeContent></div></section>

    <section className="section-space bg-stone-100"><div className="container-page"><div className="section-title-row"><div><SectionTag>Năng lực cốt lõi</SectionTag><h2 className="heading-section">Một đối tác.<br/><span>Trọn giải pháp.</span></h2></div><p>Hệ sinh thái dịch vụ khép kín giúp dự án đồng bộ, tối ưu chi phí và giảm đầu mối phối hợp.</p></div><div className="mt-12 grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{services.map(({icon:Icon,title,text}, index) => <FadeContent delay={index*.06} key={title}><article className="group h-full rounded-2xl border border-slate-200 bg-white p-7 transition duration-300 hover:-translate-y-1 hover:border-orange-300 hover:shadow-xl hover:shadow-slate-900/5"><div className="flex items-start justify-between"><span className="grid size-13 place-items-center rounded-2xl bg-emerald-950 text-white"><Icon className="size-6" /></span><span className="text-sm font-bold text-slate-300">0{index+1}</span></div><h3 className="mt-8 font-display text-xl font-bold text-emerald-950">{title}</h3><p className="mt-3 text-base leading-7 text-slate-600">{text}</p><Link className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-orange-700" to="/dich-vu">Xem chi tiết <ChevronRight className="size-4 transition group-hover:translate-x-1" /></Link></article></FadeContent>)}</div></div></section>

    <section className="section-space bg-emerald-950 text-white"><div className="container-page"><div className="section-title-row section-title-dark"><div><SectionTag light>Dự án tiêu biểu</SectionTag><h2 className="heading-section text-white">Năng lực được chứng minh<br/><span>bằng công trình thực tế.</span></h2></div><Button variant="outline" asChild className="border-white/25 bg-transparent text-white hover:bg-white hover:text-emerald-950"><Link to="/du-an">Xem tất cả dự án</Link></Button></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{projects.slice(0,3).map((project,index) => <FadeContent delay={index*.08} key={project._id}><article className="group relative min-h-[430px] overflow-hidden rounded-3xl"><img loading="lazy" className="absolute inset-0 size-full object-cover transition duration-700 group-hover:scale-105" src={project.image} alt={project.title}/><div className="absolute inset-0 bg-gradient-to-t from-emerald-950 via-emerald-950/20 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-7"><span className="rounded-full bg-orange-500/90 px-3 py-1.5 text-xs font-bold">{project.category}</span><h3 className="mt-4 font-display text-2xl font-bold leading-tight">{project.title}</h3><p className="mt-2 text-sm text-white/65">{project.location} · {project.year}</p></div></article></FadeContent>)}</div></div></section>

    <section className="section-space bg-white"><div className="container-page"><div className="section-title-row"><div><SectionTag>Thiết bị & vật tư</SectionTag><h2 className="heading-section">Dễ chọn sản phẩm.<br/><span>Dễ nhận báo giá.</span></h2></div><p>Thông tin rõ ràng, nút yêu cầu báo giá luôn dễ thấy và có đội ngũ kỹ thuật hỗ trợ lựa chọn.</p></div><div className="mt-12 grid gap-6 md:grid-cols-3">{products.slice(0,3).map((product,index) => <FadeContent delay={index*.06} key={product._id}><article className="overflow-hidden rounded-2xl border border-slate-200 bg-white transition hover:-translate-y-1 hover:shadow-xl"><div className="relative aspect-[4/3] overflow-hidden bg-slate-100"><img loading="lazy" className="size-full object-cover transition duration-500 hover:scale-105" src={product.image} alt={product.name}/><span className="absolute left-4 top-4 rounded-full bg-white px-3 py-1.5 text-xs font-bold text-emerald-950 shadow">{product.category}</span></div><div className="p-6"><h3 className="font-display text-xl font-bold text-emerald-950">{product.name}</h3><p className="mt-3 text-base font-bold text-orange-700">{formatPrice(product.price)} {product.price && `/ ${product.unit}`}</p><Button className="mt-6 w-full" variant="outline" onClick={() => openQuote(product.name)}>Yêu cầu báo giá <ArrowRight className="size-4" /></Button></div></article></FadeContent>)}</div><div className="mt-9 text-center"><Button asChild variant="ghost"><Link to="/san-pham">Xem toàn bộ sản phẩm <ArrowRight className="size-5" /></Link></Button></div></div></section>

    <section className="section-space bg-stone-100"><div className="container-page"><div className="text-center"><SectionTag center>Quy trình hợp tác</SectionTag><h2 className="heading-section">Rõ ràng trong từng <span>bước đi.</span></h2></div><div className="mt-12 grid gap-4 md:grid-cols-5">{[[Phone,"Tiếp nhận yêu cầu"],[ClipboardCheck,"Khảo sát & tư vấn"],[Ruler,"Thiết kế & báo giá"],[Building2,"Sản xuất & thi công"],[BadgeCheck,"Nghiệm thu & bảo hành"]].map(([Icon,title],index) => {const C=Icon as typeof Phone; return <div className="relative rounded-2xl bg-white p-5 text-center" key={String(title)}><span className="mx-auto grid size-12 place-items-center rounded-full bg-orange-50 text-orange-700"><C className="size-6"/></span><span className="mt-4 block text-xs font-black text-slate-300">BƯỚC 0{index+1}</span><h3 className="mt-2 text-sm font-bold text-emerald-950">{String(title)}</h3></div>})}</div></div></section>

    <section className="bg-orange-600 py-16 text-white"><div className="container-page flex flex-col items-start justify-between gap-8 lg:flex-row lg:items-center"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-orange-100">Bắt đầu một dự án</p><h2 className="mt-3 max-w-3xl font-display text-3xl font-bold leading-tight sm:text-4xl">Bạn có một bài toán kỹ thuật? Hãy để chúng tôi cùng giải quyết.</h2></div><Button size="lg" className="shrink-0 bg-white text-orange-700 hover:bg-emerald-950 hover:text-white" onClick={() => openQuote()}>Nhận tư vấn miễn phí <ArrowRight className="size-5" /></Button></div></section>
  </>
}

function SectionTag({ children, light, center }: { children: React.ReactNode; light?: boolean; center?: boolean }) { return <p className={`mb-5 flex items-center gap-3 text-xs font-extrabold uppercase tracking-[.2em] ${center ? "justify-center" : ""} ${light ? "text-orange-300" : "text-orange-700"}`}><span className="h-0.5 w-8 bg-orange-500" />{children}</p> }
