import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { CalendarClock, Factory, Search, UserCheck } from "lucide-react"
import { useEffect, useState, type FormEvent } from "react"
import { StaffShell } from "@/components/staff/staff-shell"
import { Pagination } from "@/components/pagination"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { usePageMeta } from "@/hooks/use-page-meta"
import { staffClient } from "@/lib/staff-client"
import { cn } from "@/lib/utils"
import type { StaffWorkOrder, WorkOrderStatus } from "@/types/staff"

const labels: Record<WorkOrderStatus, string> = { awaiting_contract: "Chờ hợp đồng / PO", awaiting_deposit: "Chờ đặt cọc", scheduled: "Đã lên lịch", in_progress: "Đang thực hiện", quality_check: "Kiểm tra chất lượng", ready_for_delivery: "Sẵn sàng bàn giao", completed: "Đã hoàn thành", cancelled: "Đã hủy" }
const transitions: Record<WorkOrderStatus, WorkOrderStatus[]> = { awaiting_contract: ["awaiting_deposit", "scheduled", "cancelled"], awaiting_deposit: ["scheduled", "cancelled"], scheduled: ["in_progress", "cancelled"], in_progress: ["quality_check", "cancelled"], quality_check: ["in_progress", "ready_for_delivery"], ready_for_delivery: ["completed"], completed: [], cancelled: [] }
const money = new Intl.NumberFormat("vi-VN", { style: "currency", currency: "VND" })

export function StaffWorkOrdersPage() {
  usePageMeta("Công việc sau báo giá", "Quản lý hợp đồng, đặt cọc, kế hoạch sản xuất và bàn giao.")
  const client = useQueryClient()
  const [filters, setFilters] = useState({ q: "", status: "", assigned: "" })
  const [page, setPage] = useState(1)
  const [selected, setSelected] = useState("")
  const list = useQuery({ queryKey: ["staff", "work-orders", filters, page], queryFn: () => staffClient.workOrders({ ...filters, page }) })
  const detail = useQuery({ queryKey: ["staff", "work-order", selected], queryFn: () => staffClient.workOrder(selected), enabled: Boolean(selected) })
  useEffect(() => setPage(1), [filters])
  useEffect(() => { const items = list.data?.data.items; if (items?.length && !items.some(item => item._id === selected)) setSelected(items[0]._id) }, [list.data, selected])
  const refresh = () => { void client.invalidateQueries({ queryKey: ["staff", "work-orders"] }); void client.invalidateQueries({ queryKey: ["staff", "work-order", selected] }) }
  const update = useMutation({ mutationFn: (body: Parameters<typeof staffClient.updateWorkOrder>[1]) => staffClient.updateWorkOrder(selected, body), onSuccess: refresh })
  return <StaffShell title="Công việc sau báo giá" description="Theo dõi từ hợp đồng, đặt cọc, kế hoạch thực hiện đến kiểm tra chất lượng và bàn giao.">
    <div className="mb-5 grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-[1fr_220px_180px]"><label className="relative"><Search className="absolute left-3 top-3.5 size-5 text-slate-400"/><Input className="pl-10" value={filters.q} onChange={event => setFilters({ ...filters, q: event.target.value })} placeholder="Mã công việc, hợp đồng, PO..."/></label><Select value={filters.status} onChange={status => setFilters({ ...filters, status })} first="Mọi trạng thái" options={Object.entries(labels)}/><Select value={filters.assigned} onChange={assigned => setFilters({ ...filters, assigned })} first="Tất cả phụ trách" options={[["mine", "Của tôi"], ["unassigned", "Chưa phân công"]]}/></div>
    <div className="grid gap-5 xl:grid-cols-[390px_1fr]"><div><div className="space-y-3">{list.data?.data.items.map(item => <button key={item._id} onClick={() => setSelected(item._id)} className={cn("w-full rounded-2xl border bg-white p-5 text-left shadow-sm", selected === item._id && "border-orange-500 ring-2 ring-orange-100")}><div className="flex justify-between gap-3"><strong className="text-emerald-950">{item.code}</strong><span className="font-bold text-orange-700">{money.format(item.agreedTotal)}</span></div><p className="mt-2 font-bold text-slate-700">{item.customer.name}</p><p className="mt-2 text-sm text-emerald-700">{labels[item.status]}</p></button>)}{list.isLoading && <p className="rounded-2xl bg-white p-5">Đang tải...</p>}{list.error && <p role="alert" className="rounded-2xl bg-red-50 p-4 text-red-700">{list.error.message}</p>}{!list.isLoading && !list.data?.data.items.length && <p className="rounded-2xl bg-white p-6 text-center text-slate-500">Chưa có công việc phù hợp.</p>}</div><Pagination page={list.data?.data.page || page} pages={list.data?.data.pages || 1} onChange={setPage}/></div>{detail.data?.data ? <WorkOrderDetail item={detail.data.data} busy={update.isPending} error={update.error as Error | null} onUpdate={body => update.mutate(body)}/> : <div className="rounded-3xl border bg-white p-10 text-center text-slate-500">Chọn một công việc để xử lý.</div>}</div>
  </StaffShell>
}

function WorkOrderDetail({ item, busy, error, onUpdate }: { item: StaffWorkOrder; busy: boolean; error: Error | null; onUpdate: (body: Parameters<typeof staffClient.updateWorkOrder>[1]) => void }) {
  const [form, setForm] = useState({ contractReference: item.contractReference || "", purchaseOrderReference: item.purchaseOrderReference || "", depositRequired: String(item.depositRequired || 0), depositPaid: String(item.depositPaid || 0), plannedStartAt: item.plannedStartAt?.slice(0, 16) || "", plannedDeliveryAt: item.plannedDeliveryAt?.slice(0, 16) || "" })
  const [status, setStatus] = useState("")
  const [message, setMessage] = useState("")
  useEffect(() => { setForm({ contractReference: item.contractReference || "", purchaseOrderReference: item.purchaseOrderReference || "", depositRequired: String(item.depositRequired || 0), depositPaid: String(item.depositPaid || 0), plannedStartAt: item.plannedStartAt?.slice(0, 16) || "", plannedDeliveryAt: item.plannedDeliveryAt?.slice(0, 16) || "" }); setStatus(""); setMessage("") }, [item])
  const save = (event: FormEvent) => { event.preventDefault(); onUpdate({ ...form, depositRequired: Number(form.depositRequired), depositPaid: Number(form.depositPaid) }) }
  return <article className="rounded-3xl border bg-white p-6 shadow-sm sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-black uppercase tracking-wider text-orange-700">{item.code}</p><h2 className="mt-2 font-display text-3xl font-bold text-emerald-950">{item.request.title}</h2><p className="mt-2 text-slate-600">Khách hàng: {item.customer.name} · Báo giá {item.quotation.code}</p></div><Button variant={item.assignedTo ? "outline" : "default"} disabled={busy} onClick={() => onUpdate({ assignedTo: item.assignedTo ? "unassigned" : "me" })}><UserCheck className="size-5"/>{item.assignedTo ? `Phụ trách: ${item.assignedTo.name}` : "Nhận phụ trách"}</Button></div><div className="mt-6 grid gap-4 rounded-2xl bg-emerald-50 p-5 sm:grid-cols-3"><p><span className="block text-xs font-bold text-slate-500">Giá trị thống nhất</span><strong>{money.format(item.agreedTotal)}</strong></p><p><span className="block text-xs font-bold text-slate-500">Đã đặt cọc</span><strong>{money.format(item.depositPaid)}</strong></p><p><span className="block text-xs font-bold text-slate-500">Trạng thái</span><strong>{labels[item.status]}</strong></p></div>
    <form className="mt-6 grid gap-4 sm:grid-cols-2" onSubmit={save}><Field label="Số hợp đồng"><Input value={form.contractReference} onChange={event => setForm({ ...form, contractReference: event.target.value })}/></Field><Field label="Số PO"><Input value={form.purchaseOrderReference} onChange={event => setForm({ ...form, purchaseOrderReference: event.target.value })}/></Field><Field label="Đặt cọc yêu cầu"><Input type="number" min="0" value={form.depositRequired} onChange={event => setForm({ ...form, depositRequired: event.target.value })}/></Field><Field label="Đặt cọc đã nhận"><Input type="number" min="0" value={form.depositPaid} onChange={event => setForm({ ...form, depositPaid: event.target.value })}/></Field><Field label="Ngày bắt đầu dự kiến"><Input type="datetime-local" value={form.plannedStartAt} onChange={event => setForm({ ...form, plannedStartAt: event.target.value })}/></Field><Field label="Ngày bàn giao dự kiến"><Input type="datetime-local" value={form.plannedDeliveryAt} onChange={event => setForm({ ...form, plannedDeliveryAt: event.target.value })}/></Field><Button className="sm:col-span-2 sm:justify-self-start" variant="outline" disabled={busy}>Lưu hồ sơ công việc</Button></form>
    {transitions[item.status].length > 0 && <form className="mt-7 grid gap-3 border-t pt-6 sm:grid-cols-[240px_1fr_auto]" onSubmit={event => { event.preventDefault(); if (status) onUpdate({ status: status as WorkOrderStatus, message }) }}><Select value={status} onChange={setStatus} first="Chọn bước tiếp theo" options={transitions[item.status].map(value => [value, labels[value]])}/><Textarea className="min-h-11" value={message} onChange={event => setMessage(event.target.value)} placeholder="Nội dung cập nhật cho khách hàng"/><Button disabled={busy || !status}>Cập nhật tiến độ</Button></form>}
    {error && <p role="alert" className="mt-4 rounded-xl bg-red-50 p-4 font-semibold text-red-700">{error.message}</p>}
    <section className="mt-7 border-t pt-6"><h3 className="flex items-center gap-2 font-display text-xl font-bold text-emerald-950"><Factory className="size-5 text-orange-600"/>Lịch sử</h3><ol className="mt-4 space-y-3">{item.timeline.map((entry, index) => <li className="flex gap-3 text-sm" key={`${entry.at}-${index}`}><span className="mt-1.5 size-2 shrink-0 rounded-full bg-orange-500"/><div><strong>{labels[entry.status as WorkOrderStatus] || entry.status}</strong>{entry.message && <p className="mt-1 text-slate-500">{entry.message}</p>}<time className="mt-1 flex items-center gap-1 text-xs text-slate-400"><CalendarClock className="size-3"/>{new Date(entry.at).toLocaleString("vi-VN")}</time></div></li>)}</ol></section>
  </article>
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-sm font-bold text-slate-700">{label}<span className="mt-2 block">{children}</span></label> }
function Select({ value, onChange, first, options }: { value: string; onChange: (value: string) => void; first: string; options: string[][] }) { return <select className="field-select" value={value} onChange={event => onChange(event.target.value)}><option value="">{first}</option>{options.map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select> }
