import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { Download, FileText, MessageSquareText, Plus, Search, Send, UserCheck } from "lucide-react"
import { useEffect, useState, type FormEvent } from "react"
import { useSearchParams } from "react-router-dom"
import { StaffShell } from "@/components/staff/staff-shell"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { usePageMeta } from "@/hooks/use-page-meta"
import { staffClient } from "@/lib/staff-client"
import { cn } from "@/lib/utils"
import type { Priority, RequestStatus, StaffRequestDetail } from "@/types/staff"

const statusNames: Record<RequestStatus, string> = { submitted: "Mới gửi", reviewing: "Đang đánh giá", need_more_info: "Chờ bổ sung", quoted: "Đã báo giá", accepted: "Đã chấp thuận", rejected: "Từ chối", cancelled: "Đã hủy" }
const priorityNames: Record<Priority, string> = { low: "Thấp", normal: "Bình thường", high: "Cao", urgent: "Khẩn" }
const money = new Intl.NumberFormat("vi-VN", { style: "currency", currency: "VND" })

export function StaffRequestsPage() {
  usePageMeta("Yêu cầu dịch vụ", "Xử lý hồ sơ kỹ thuật, trao đổi và báo giá.")
  const [params] = useSearchParams(); const client = useQueryClient()
  const [filters, setFilters] = useState({ q: "", status: "", priority: params.get("priority") || "", assigned: params.get("assigned") || "" })
  const [selected, setSelected] = useState("")
  const list = useQuery({ queryKey: ["staff", "requests", filters], queryFn: () => staffClient.requests(filters) })
  const detail = useQuery({ queryKey: ["staff", "request", selected], queryFn: () => staffClient.request(selected), enabled: Boolean(selected) })
  useEffect(() => { if (!selected && list.data?.data.items[0]) setSelected(list.data.data.items[0]._id) }, [list.data, selected])
  const refresh = () => { client.invalidateQueries({ queryKey: ["staff", "requests"] }); client.invalidateQueries({ queryKey: ["staff", "request", selected] }); client.invalidateQueries({ queryKey: ["staff", "dashboard"] }) }
  const update = useMutation({ mutationFn: (body: Parameters<typeof staffClient.updateRequest>[1]) => staffClient.updateRequest(selected, body), onSuccess: refresh })
  const message = useMutation({ mutationFn: (body: { content: string; visibility: "customer" | "internal" }) => staffClient.sendMessage(selected, body.content, body.visibility), onSuccess: refresh })
  const quotation = useMutation({ mutationFn: (body: Parameters<typeof staffClient.createQuotation>[1]) => staffClient.createQuotation(selected, body), onSuccess: refresh })
  const sendQuote = useMutation({ mutationFn: (id: string) => staffClient.sendQuotation(selected, id), onSuccess: refresh })
  return <StaffShell title="Yêu cầu dịch vụ" description="Một nơi để đánh giá kỹ thuật, trao đổi với khách hàng và phát hành báo giá có phiên bản.">
    <div className="mb-5 grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-[1fr_190px_170px_170px]"><label className="relative"><Search className="absolute left-3 top-3.5 size-5 text-slate-400"/><Input className="pl-10" value={filters.q} onChange={event => setFilters({ ...filters, q: event.target.value })} placeholder="Tìm mã, tiêu đề, khách hàng..."/></label><Filter value={filters.status} onChange={status => setFilters({ ...filters, status })} first="Mọi trạng thái" options={Object.entries(statusNames)}/><Filter value={filters.priority} onChange={priority => setFilters({ ...filters, priority })} first="Mọi ưu tiên" options={Object.entries(priorityNames)}/><Filter value={filters.assigned} onChange={assigned => setFilters({ ...filters, assigned })} first="Tất cả phụ trách" options={[["mine", "Của tôi"], ["unassigned", "Chưa phân công"]]}/></div>
    <div className="grid gap-5 xl:grid-cols-[390px_1fr]"><div className="space-y-3">{list.isLoading && <p className="rounded-2xl bg-white p-5">Đang tải danh sách...</p>}{list.data?.data.items.map(item => <button key={item._id} onClick={() => setSelected(item._id)} className={cn("w-full rounded-2xl border bg-white p-5 text-left shadow-sm transition hover:border-orange-300", selected === item._id && "border-orange-500 ring-2 ring-orange-100")}><div className="flex items-start justify-between gap-3"><div><strong className="font-display text-lg text-emerald-950">{item.title}</strong><p className="mt-1 text-sm font-bold text-slate-500">{item.code}</p></div><span className="rounded-full bg-orange-50 px-3 py-1 text-xs font-bold text-orange-800">{priorityNames[item.priority]}</span></div><p className="mt-3 text-slate-700">{item.customer.name}</p><div className="mt-3 flex items-center justify-between text-sm"><span className="font-bold text-emerald-700">{statusNames[item.status]}</span><span className="text-slate-500">{new Date(item.createdAt).toLocaleDateString("vi-VN")}</span></div></button>)}{!list.isLoading && !list.data?.data.items.length && <p className="rounded-2xl bg-white p-6 text-center text-slate-500">Không có hồ sơ phù hợp.</p>}</div>
      <div>{detail.data?.data ? <RequestDetail detail={detail.data.data} busy={update.isPending || message.isPending || quotation.isPending || sendQuote.isPending} error={(update.error || message.error || quotation.error || sendQuote.error) as Error | null} onUpdate={body => update.mutate(body)} onMessage={body => message.mutate(body)} onQuotation={body => quotation.mutate(body)} onSendQuote={id => sendQuote.mutate(id)}/> : <div className="rounded-3xl border bg-white p-10 text-center text-slate-500">Chọn một yêu cầu để xử lý.</div>}</div></div>
  </StaffShell>
}

function RequestDetail({ detail, busy, error, onUpdate, onMessage, onQuotation, onSendQuote }: { detail: StaffRequestDetail; busy: boolean; error: Error | null; onUpdate: (body: Parameters<typeof staffClient.updateRequest>[1]) => void; onMessage: (body: { content: string; visibility: "customer" | "internal" }) => void; onQuotation: (body: Parameters<typeof staffClient.createQuotation>[1]) => void; onSendQuote: (id: string) => void }) {
  const { request, messages, quotations } = detail
  const [status, setStatus] = useState<RequestStatus>(request.status); const [statusMessage, setStatusMessage] = useState(""); const [content, setContent] = useState(""); const [visibility, setVisibility] = useState<"customer" | "internal">("customer")
  useEffect(() => { setStatus(request.status); setStatusMessage(""); setContent("") }, [request._id, request.status])
  const download = async (attachmentId: string, filename: string, messageId?: string) => { const blob = messageId ? await staffClient.downloadMessageAttachment(request._id, messageId, attachmentId) : await staffClient.downloadAttachment(request._id, attachmentId); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url) }
  return <article className="space-y-6"><section className="rounded-3xl border bg-white p-6 shadow-sm sm:p-8"><div className="flex flex-col justify-between gap-4 md:flex-row"><div><p className="text-sm font-black uppercase tracking-wider text-orange-700">{request.code}</p><h2 className="mt-2 font-display text-3xl font-bold text-emerald-950">{request.title}</h2><p className="mt-2 text-slate-600">{request.customer.name} · {request.customer.company || request.customer.email}</p></div><Button onClick={() => onUpdate({ assignedTo: request.assignedTo ? "unassigned" : "me" })} disabled={busy} variant={request.assignedTo ? "outline" : "default"}><UserCheck className="size-5"/>{request.assignedTo ? `Phụ trách: ${request.assignedTo.name}` : "Nhận phụ trách"}</Button></div>
      <div className="mt-6 rounded-2xl bg-slate-50 p-5"><p className="leading-7 text-slate-800">{request.description}</p><div className="mt-4 flex flex-wrap gap-2 text-sm font-bold text-slate-600"><span>Vật liệu: {request.material || "–"}</span><span>· Số lượng: {request.quantity || "–"}</span><span>· Kích thước: {request.dimensions || "–"}</span><span>· Ngân sách: {request.budget || "–"}</span></div>{request.attachments.length > 0 && <div className="mt-4 flex flex-wrap gap-2">{request.attachments.map(file => <Button key={file._id} variant="outline" size="sm" onClick={() => download(file._id, file.originalName)}><Download className="size-4"/>{file.originalName}</Button>)}</div>}</div>
      {error && <p className="mt-4 rounded-xl bg-red-50 p-4 font-semibold text-red-700">{error.message}</p>}
      <form onSubmit={(event: FormEvent) => { event.preventDefault(); onUpdate({ status, message: statusMessage }) }} className="mt-6 grid gap-3 lg:grid-cols-[190px_160px_1fr_auto]"><Filter value={status} onChange={value => setStatus(value as RequestStatus)} first="Chọn trạng thái" options={Object.entries(statusNames)}/><select className="field-select" value={request.priority} onChange={event => onUpdate({ priority: event.target.value as Priority })}>{Object.entries(priorityNames).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><Input value={statusMessage} onChange={event => setStatusMessage(event.target.value)} placeholder={status === "need_more_info" ? "Thông tin khách cần bổ sung (bắt buộc)" : "Nội dung cập nhật"}/><Button disabled={busy}>Lưu</Button></form>
    </section>
    <section className="grid gap-6 lg:grid-cols-2"><div className="rounded-3xl border bg-white p-6"><h3 className="flex items-center gap-2 font-display text-2xl font-bold text-emerald-950"><MessageSquareText className="size-6 text-orange-600"/>Trao đổi</h3><div className="mt-5 max-h-96 space-y-3 overflow-y-auto pr-1">{messages.map(item => <div key={item._id} className={cn("rounded-2xl p-4", item.visibility === "internal" ? "bg-amber-50" : item.senderRole === "customer" ? "bg-slate-100" : "bg-emerald-50")}><div className="flex justify-between gap-3 text-xs font-bold text-slate-500"><span>{item.visibility === "internal" ? "Ghi chú nội bộ" : item.senderRole === "customer" ? "Khách hàng" : item.sender?.name || "Nhân viên"}</span><span>{new Date(item.createdAt).toLocaleString("vi-VN")}</span></div><p className="mt-2 whitespace-pre-wrap text-slate-800">{item.content}</p>{item.attachments.map(file => <button key={file._id} onClick={() => download(file._id, file.originalName, item._id)} className="mt-2 flex items-center gap-2 font-bold text-orange-700"><Download className="size-4"/>{file.originalName}</button>)}</div>)}</div><form className="mt-5 space-y-3" onSubmit={event => { event.preventDefault(); if (content.trim()) onMessage({ content: content.trim(), visibility }) }}><Textarea value={content} onChange={event => setContent(event.target.value)} placeholder="Nhập nội dung trao đổi hoặc ghi chú..."/><div className="flex flex-wrap items-center justify-between gap-3"><select className="field-select max-w-48" value={visibility} onChange={event => setVisibility(event.target.value as "customer" | "internal")}><option value="customer">Gửi khách hàng</option><option value="internal">Chỉ nội bộ</option></select><Button disabled={busy || !content.trim()}><Send className="size-4"/>Gửi</Button></div></form></div>
      <QuotationPanel requestId={request._id} quotations={quotations} busy={busy} onCreate={onQuotation} onSend={onSendQuote}/></section>
    </article>
}

function QuotationPanel({ quotations, busy, onCreate, onSend }: { requestId: string; quotations: StaffRequestDetail["quotations"]; busy: boolean; onCreate: (body: Parameters<typeof staffClient.createQuotation>[1]) => void; onSend: (id: string) => void }) {
  const [open, setOpen] = useState(false); const [items, setItems] = useState([{ description: "", quantity: 1, unit: "cái", unitPrice: 0 }]); const [taxRate, setTaxRate] = useState(10); const [validUntil, setValidUntil] = useState(""); const [leadTime, setLeadTime] = useState(""); const [paymentTerms, setPaymentTerms] = useState(""); const [notes, setNotes] = useState("")
  const total = items.reduce((sum, item) => sum + item.quantity * item.unitPrice, 0) * (1 + taxRate / 100)
  const submit = (status: "draft" | "sent") => onCreate({ items, taxRate, validUntil, leadTime, paymentTerms, notes, status })
  return <div className="rounded-3xl border bg-white p-6"><div className="flex items-center justify-between gap-3"><h3 className="flex items-center gap-2 font-display text-2xl font-bold text-emerald-950"><FileText className="size-6 text-orange-600"/>Báo giá</h3><Button size="sm" onClick={() => setOpen(!open)}><Plus className="size-4"/>Tạo báo giá</Button></div>{open && <div className="mt-5 space-y-4 rounded-2xl bg-slate-50 p-4">{items.map((item, index) => <div className="grid gap-2 sm:grid-cols-[1fr_70px_80px_120px]" key={index}><Input value={item.description} onChange={event => setItems(items.map((value, i) => i === index ? { ...value, description: event.target.value } : value))} placeholder="Hạng mục"/><Input type="number" min="0.01" step="0.01" value={item.quantity} onChange={event => setItems(items.map((value, i) => i === index ? { ...value, quantity: Number(event.target.value) } : value))}/><Input value={item.unit} onChange={event => setItems(items.map((value, i) => i === index ? { ...value, unit: event.target.value } : value))}/><Input type="number" min="0" value={item.unitPrice} onChange={event => setItems(items.map((value, i) => i === index ? { ...value, unitPrice: Number(event.target.value) } : value))}/></div>)}<Button type="button" size="sm" variant="outline" onClick={() => setItems([...items, { description: "", quantity: 1, unit: "cái", unitPrice: 0 }])}><Plus className="size-4"/>Thêm hạng mục</Button><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold text-slate-700">VAT (%)<Input className="mt-2" type="number" min="0" max="100" value={taxRate} onChange={event => setTaxRate(Number(event.target.value))}/></label><label className="text-sm font-bold text-slate-700">Hiệu lực đến<Input className="mt-2" type="date" value={validUntil} onChange={event => setValidUntil(event.target.value)}/></label><Input value={leadTime} onChange={event => setLeadTime(event.target.value)} placeholder="Thời gian thực hiện"/><Input value={paymentTerms} onChange={event => setPaymentTerms(event.target.value)} placeholder="Điều khoản thanh toán"/></div><Textarea value={notes} onChange={event => setNotes(event.target.value)} placeholder="Ghi chú báo giá"/><p className="text-right text-lg font-black text-emerald-950">Tạm tính: {money.format(total)}</p><div className="flex justify-end gap-2"><Button disabled={busy} variant="outline" onClick={() => submit("draft")}>Lưu nháp</Button><Button disabled={busy} onClick={() => submit("sent")}><Send className="size-4"/>Gửi khách</Button></div></div>}
    <div className="mt-5 space-y-3">{quotations.map(item => <div key={item._id} className="rounded-2xl border p-4"><div className="flex items-center justify-between"><div><strong className="text-emerald-950">{item.code} · Bản {item.version}</strong><p className="text-sm text-slate-500">Hiệu lực {new Date(item.validUntil).toLocaleDateString("vi-VN")}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black uppercase text-slate-700">{item.status}</span></div><p className="mt-3 text-right text-xl font-black text-orange-700">{money.format(item.total)}</p>{item.status === "draft" && <Button className="mt-3 w-full" size="sm" onClick={() => onSend(item._id)} disabled={busy}>Gửi bản nháp này</Button>}</div>)}{!quotations.length && <p className="py-6 text-center text-slate-500">Chưa có báo giá.</p>}</div>
  </div>
}

function Filter({ value, onChange, first, options }: { value: string; onChange: (value: string) => void; first: string; options: string[][] }) { return <select className="field-select" value={value} onChange={event => onChange(event.target.value)}><option value="">{first}</option>{options.map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select> }
