import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { MapPin, Phone, Search, UserCheck } from "lucide-react"
import { useEffect, useState, type FormEvent } from "react"
import { useSearchParams } from "react-router-dom"
import { StaffShell } from "@/components/staff/staff-shell"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { usePageMeta } from "@/hooks/use-page-meta"
import { staffClient } from "@/lib/staff-client"
import { cn } from "@/lib/utils"
import type { StaffOrder } from "@/types/staff"

const statusNames: Record<StaffOrder["status"], string> = { pending: "Chờ xác nhận", confirmed: "Đã xác nhận", preparing: "Đang chuẩn bị", shipping: "Đang giao", delivered: "Đã giao", cancelled: "Đã hủy" }
const paymentNames: Record<StaffOrder["paymentStatus"], string> = { unpaid: "Chưa thanh toán", pending: "Chờ đối soát", paid: "Đã thanh toán", refunded: "Đã hoàn tiền" }
const money = new Intl.NumberFormat("vi-VN", { style: "currency", currency: "VND" })

export function StaffOrdersPage() {
  usePageMeta("Quản lý đơn hàng", "Xác nhận tồn kho, chuẩn bị và điều phối giao hàng.")
  const [params] = useSearchParams(); const client = useQueryClient()
  const [filters, setFilters] = useState({ q: "", status: params.get("status") || "", paymentStatus: "", assigned: params.get("assigned") || "" }); const [selected, setSelected] = useState("")
  const list = useQuery({ queryKey: ["staff", "orders", filters], queryFn: () => staffClient.orders(filters) })
  const detail = useQuery({ queryKey: ["staff", "order", selected], queryFn: () => staffClient.order(selected), enabled: Boolean(selected) })
  useEffect(() => { if (!selected && list.data?.data.items[0]) setSelected(list.data.data.items[0]._id) }, [list.data, selected])
  const refresh = () => { client.invalidateQueries({ queryKey: ["staff", "orders"] }); client.invalidateQueries({ queryKey: ["staff", "order", selected] }); client.invalidateQueries({ queryKey: ["staff", "dashboard"] }) }
  const update = useMutation({ mutationFn: (body: Parameters<typeof staffClient.updateOrder>[1]) => staffClient.updateOrder(selected, body), onSuccess: refresh })
  return <StaffShell title="Đơn hàng thương mại" description="Xác nhận tồn kho trước khi chuẩn bị hàng, theo dõi thanh toán và giao nhận."><div className="mb-5 grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-[1fr_180px_180px_170px]"><label className="relative"><Search className="absolute left-3 top-3.5 size-5 text-slate-400"/><Input className="pl-10" value={filters.q} onChange={event => setFilters({ ...filters, q: event.target.value })} placeholder="Mã đơn, người nhận, điện thoại..."/></label><Filter value={filters.status} onChange={status => setFilters({ ...filters, status })} first="Mọi trạng thái" options={Object.entries(statusNames)}/><Filter value={filters.paymentStatus} onChange={paymentStatus => setFilters({ ...filters, paymentStatus })} first="Mọi thanh toán" options={Object.entries(paymentNames)}/><Filter value={filters.assigned} onChange={assigned => setFilters({ ...filters, assigned })} first="Tất cả phụ trách" options={[["mine", "Của tôi"], ["unassigned", "Chưa phân công"]]}/></div>
    <div className="grid gap-5 xl:grid-cols-[390px_1fr]"><div className="space-y-3">{list.data?.data.items.map(item => <button key={item._id} onClick={() => setSelected(item._id)} className={cn("w-full rounded-2xl border bg-white p-5 text-left shadow-sm transition hover:border-orange-300", selected === item._id && "border-orange-500 ring-2 ring-orange-100")}><div className="flex justify-between gap-3"><strong className="text-lg text-emerald-950">{item.code}</strong><span className="text-sm font-black text-orange-700">{money.format(item.total)}</span></div><p className="mt-2 text-slate-700">{item.shippingAddress.recipientName}</p><div className="mt-3 flex justify-between text-sm"><span className="font-bold text-emerald-700">{statusNames[item.status]}</span><span className="text-slate-500">{new Date(item.createdAt).toLocaleDateString("vi-VN")}</span></div></button>)}{list.isLoading && <p className="rounded-2xl bg-white p-5">Đang tải đơn hàng...</p>}{!list.isLoading && !list.data?.data.items.length && <p className="rounded-2xl bg-white p-6 text-center text-slate-500">Không có đơn phù hợp.</p>}</div>{detail.data?.data ? <OrderDetail order={detail.data.data} busy={update.isPending} error={update.error as Error | null} onUpdate={body => update.mutate(body)}/> : <div className="rounded-3xl border bg-white p-10 text-center text-slate-500">Chọn một đơn hàng để xử lý.</div>}</div></StaffShell>
}

function OrderDetail({ order, busy, error, onUpdate }: { order: StaffOrder; busy: boolean; error: Error | null; onUpdate: (body: Parameters<typeof staffClient.updateOrder>[1]) => void }) {
  const [status, setStatus] = useState(order.status); const [paymentStatus, setPaymentStatus] = useState(order.paymentStatus); const [message, setMessage] = useState(""); const [internalNote, setInternalNote] = useState(order.internalNote || "")
  useEffect(() => { setStatus(order.status); setPaymentStatus(order.paymentStatus); setMessage(""); setInternalNote(order.internalNote || "") }, [order])
  return <article className="rounded-3xl border bg-white p-6 shadow-sm sm:p-8"><div className="flex flex-col justify-between gap-4 md:flex-row"><div><p className="text-sm font-black uppercase tracking-wider text-orange-700">{order.code}</p><h2 className="mt-2 font-display text-3xl font-bold text-emerald-950">{order.shippingAddress.recipientName}</h2><p className="mt-2 text-slate-600">{order.customer.name} · {order.paymentMethod === "cod" ? "Thanh toán khi nhận" : "Chuyển khoản"}</p></div><Button onClick={() => onUpdate({ assignedTo: order.assignedTo ? "unassigned" : "me" })} disabled={busy} variant={order.assignedTo ? "outline" : "default"}><UserCheck className="size-5"/>{order.assignedTo ? `Phụ trách: ${order.assignedTo.name}` : "Nhận phụ trách"}</Button></div>
    <div className="mt-6 grid gap-4 rounded-2xl bg-slate-50 p-5 md:grid-cols-2"><p className="flex gap-3"><MapPin className="mt-1 size-5 shrink-0 text-orange-600"/><span>{order.shippingAddress.addressLine}, {order.shippingAddress.ward && `${order.shippingAddress.ward}, `}{order.shippingAddress.district}, {order.shippingAddress.province}</span></p><a className="flex min-h-11 items-center gap-3 font-bold text-emerald-800" href={`tel:${order.shippingAddress.phone}`}><Phone className="size-5 text-orange-600"/>{order.shippingAddress.phone}</a></div>
    <div className="mt-6 overflow-x-auto"><table className="w-full min-w-[560px] text-left"><thead className="border-b text-sm text-slate-500"><tr><th className="py-3">Sản phẩm</th><th>SL</th><th>Đơn giá</th><th className="text-right">Thành tiền</th></tr></thead><tbody>{order.items.map(item => <tr key={item._id} className="border-b"><td className="py-4 font-bold text-emerald-950">{item.name}<span className="block text-xs font-normal text-slate-500">{item.sku}</span></td><td>{item.quantity} {item.unit}</td><td>{money.format(item.price)}</td><td className="text-right font-bold">{money.format(item.lineTotal)}</td></tr>)}</tbody></table><p className="mt-5 text-right font-display text-2xl font-black text-orange-700">Tổng: {money.format(order.total)}</p></div>
    {error && <p className="mt-4 rounded-xl bg-red-50 p-4 font-semibold text-red-700">{error.message}</p>}
    <form className="mt-6 grid gap-3 lg:grid-cols-[180px_180px_1fr_auto]" onSubmit={(event: FormEvent) => { event.preventDefault(); onUpdate({ status, paymentStatus, message }) }}><Filter value={status} onChange={value => setStatus(value as StaffOrder["status"])} first="Trạng thái đơn" options={Object.entries(statusNames)}/><Filter value={paymentStatus} onChange={value => setPaymentStatus(value as StaffOrder["paymentStatus"])} first="Thanh toán" options={Object.entries(paymentNames)}/><Input value={message} onChange={event => setMessage(event.target.value)} placeholder="Ghi chú cập nhật cho khách"/><Button disabled={busy}>Cập nhật</Button></form>
    <div className="mt-6"><label className="text-sm font-bold text-slate-700">Ghi chú nội bộ<Textarea className="mt-2" value={internalNote} onChange={event => setInternalNote(event.target.value)} placeholder="Thông tin kho, hóa đơn VAT, vận chuyển..."/></label><Button className="mt-3" variant="outline" disabled={busy} onClick={() => onUpdate({ internalNote })}>Lưu ghi chú</Button></div>
  </article>
}

function Filter({ value, onChange, first, options }: { value: string; onChange: (value: string) => void; first: string; options: string[][] }) { return <select className="field-select" value={value} onChange={event => onChange(event.target.value)}><option value="">{first}</option>{options.map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select> }
